snapshot 2025-11-07T15:30:53.361546+00:00

diff --git a/tests/max-count-overread b/tests/max-count-overread
--- a/tests/max-count-overread
+++ b/tests/max-count-overread
@@ -18,4 +18,14 @@ printf 'x\nx\nx\n' >in || framework_failure
 (grep -m2 x >/dev/null && head -n1) <in >out || fail=1
 compare exp out || fail=1
 
+# The following two tests would fail before v3.11-70
+echo x > in || framework_failure_
+echo in > exp || framework_failure_
+grep -l -m1 . in > out || fail=1
+compare exp out || fail=1
+
+# Ensure that this prints nothing and exits successfully.
+grep -q -m1 . in > out || fail=1
+compare /dev/null out || fail=1
+
 Exit $fail
